from pythor.datamodules.dataloaders_base import ThorDataLoaders
from pythor.datamodules.cifar10_dataloaders import CIFAR10DataLoaders
from pythor.datamodules.mnist_dataloaders import MNISTDataLoaders
# from pythor.datamodules.stl10_dataloaders import STL10DataLoaders